### ISSUE TITLE
Add parsers for CWL documents 

### ISSUE THREAD

**Issue by lutsik** [hubentu/Rcwl#5]
Hi, is there a plan to add such functionality?

**Comment by hubentu** [comment]
Hi @lutsik ,
Yes, the function `readCWL` can parse CWL into R. It can read local or downloadable URL directly.
For example, 
```r
> bwa <- readCWL("https://raw.githubusercontent.com/hubentu/RcwlRecipes/master/cwl/bwa.cwl")
> bwa
```
```
 class: cwlParam
  cwlClass: CommandLineTool
  cwlVersion: v1.0
  baseCommand: bwa mem
 requirements:
 - class: DockerRequirement
   dockerPull: biocontainers/bwa:v0.7.17-3-deb_cv1
 inputs:
   threads (int): -t
   RG (string): -R
   Ref (File):
   FQ1 (File):
   FQ2 (File?):
 outputs:
 sam:
   type: File
   outputBinding:
     glob: '*.sam'
 stdout: bwaOutput.sam
```

There is another more versatile function `cwlLoad` from the [`RcwlPipeline`](http://bioconductor.org/packages/release/bioc/html/RcwlPipelines.html) package. It can load CWL from id, URI and github path. For example, to load a workflow from a github repo.
```r
> pf <- cwlLoad("common-workflow-library/bio-cwl-tools", cwlfile = "sratoolkit/prefetch_fastq.cwl")
> pf
```

```
class: cwlStepParam 
 cwlClass: Workflow 
 cwlVersion: v1.0 
requirements:
MultipleInputFeatureRequirement: {}
StepInputExpressionRequirement: {}
InlineJavascriptRequirement: {}
inputs:
  sra_accession (string):  
outputs:
fastq_files:
  format: edam:format_1931
  type: File[]
  outputSource: fastq_dump/all_fastq_files
fastq_file_1:
  format: edam:format_1931
  type: File
  outputSource: rename_fastq1/outfile
fastq_file_2:
  format: edam:format_1931
  type: File?
  outputSource: fastq_dump/fastq_file_2
steps:
  prefetch:
    run: prefetch.cwl
    accession: sra_accession
    out: sra_file
  fastq_dump:
    run: fastq_dump.cwl
    sra_file: prefetch/sra_file
    split_files: 
    out: all_fastq_files fastq_file_1 fastq_file_2
  rename_fastq1:
    run: rename_fastq1.cwl
    srcfile: fastq_dump/fastq_file_1
    fastq2: fastq_dump/fastq_file_2
    accession: sra_accession
    newname: 
    out: outfile
```
